// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_30_poles = "CgkI_4i0zvscEAIQBw"; // <GPGSID>
        public const string leaderboard_spinning_distance = "CgkI_4i0zvscEAIQCQ"; // <GPGSID>
        public const string achievement_first_step = "CgkI_4i0zvscEAIQAQ"; // <GPGSID>
        public const string achievement_20_obstacles = "CgkI_4i0zvscEAIQBQ"; // <GPGSID>
        public const string leaderboard_normal_distance = "CgkI_4i0zvscEAIQCA"; // <GPGSID>
        public const string achievement_25_poles = "CgkI_4i0zvscEAIQBg"; // <GPGSID>
        public const string achievement_15_obstacles = "CgkI_4i0zvscEAIQBA"; // <GPGSID>
        public const string achievement_high_five = "CgkI_4i0zvscEAIQAg"; // <GPGSID>
        public const string achievement_1010 = "CgkI_4i0zvscEAIQAw"; // <GPGSID>

}

